version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ~/docker-conf/rabbitmq/data:/var/lib/rabbitmq
      - ~/docker-conf/rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq-network
  network:
    rabbitmq-network:
      driver: bridge